### ISSUE TITLE
Latest version of PyCharm Edu's UI is different than the screenshots in the slides

### ISSUE THREAD

**Issue by remyroy** [ladieslearningcode/llc-intro-to-python#11]
Slide #11, #12, #27 include screenshots which are different than the latest version of PyCharm Edu's UI available on the provided link to download it. To be specific, the welcome window for PyCharm Edu has fewer elements and there is no more *Run* menu item in the main menu.

There is a high risk of confusion for the new comers with this discrepancy.

**Comment by wolever** [comment]
I'm taking new screen shots now. I'll have a PR for this in a day or two.

**Comment by wolever** [comment]
Err, and by "day" I mean "minute". See #16.

**Comment by remyroy** [comment]
I believe the textual content of the slides will need to be updated as well. For instance, on slide #26, it is mentioned that in order to execute your Python program:

```
To run the code, select Run > Run…
```

I suspect there are many other elements of the slides that make references to the old UI for PyCharm.

**Comment by christinatruong** [comment]
Updates screenshots are included in commit c7febec.
