### ISSUE TITLE
Updates following first run

### ISSUE THREAD

**Issue by evidens** [ladieslearningcode/llc-intro-to-python#2]
- [x] slide 9 – the note about which browser to use isn't terribly relevant to the Python workshop (except for the slides) @knowcliu 
- [x] slide 14 – add float and other types for consistency with int an str
- [x] slide 14 – show proper True, False (not lower case) @knowcliu
- [x] slide 14 – remove mention of list type
- [x] new slide before 15 – briefly describe functions/methods in so far as we'll be using them in the course
- [x] new slide after 21 – explain that variable names are arbitrary so people don't ascribe too much meaning to them
- [x] slide 32 – Add a note to the example that you split a math notation like `0 < x < 6` into two parts with and
- [x] slide 40 – uncomment lunch slide, it seems to be at the right spot
- [x] slide 43 – fix file open path to match console @knowcliu
- [x] new slide before 45
    - re-iterate how `for` loops work after lunch (people forget what they don't repeat)
    - demonstrate the concept of a 'block' of indented code
    - show the concepts applied to CSV data objects
- [x] slide 46 - fix demo file to remove `../exercises` since it's unnecessary

**Comment by christinatruong** [comment]
Updates merged from pull request #3.
