### ISSUE TITLE
slide 34

### ISSUE THREAD

**Issue by pennyan** [ladieslearningcode/llc-intro-to-python#36]
Hi,

When I was looking through the slides, I found there might be a potential bug on slide 34. I tried below code in python 2.7.10 and it seems to work:

>>> x = 3
>>> if (2 < x < 4):
...     print 1
... else:
...     print 0
...
1
>>>

Here is a doc link explaining it:
https://docs.python.org/2/reference/expressions.html#not-in

**Comment by hockeybuggy** [comment]
Hello @pennyan. I get the same result when I run the same thing in python 2.

```python
>>> x = 3
>>> if (2 < x < 4):
...     print 1
... else:
...     print 0
...
1
```

What seems to be the issue with side 34? Is it this line, since you can do this on a single line?: 

> In math notation you can write 0 < x < 6, but in Python, you should split these into separate comparisons.

If so, I agree with you. What about?:

> In math notation you can write 0 < x < 6, but in Python, you **could** split these into separate comparisons.

**Comment by pennyan** [comment]
Hi @hockeybuggy. Thanks for replying and sorry I didn't clearly state the problem.

I got the wrong link to the Python document in my initial issue, here's the correct one:
[https://docs.python.org/2/reference/expressions.html#comparisons](https://docs.python.org/2/reference/expressions.html#comparisons)
Read 5.9. Comparisons.

The slide 34 seems to suggest that Python does not allow such syntax, but the syntax seems to be just fine. (And it even has the benefit of saving the evaluation of the shared variables, according to the document.)

My suggestion would be to show both ways of doing comparison and the sentence maybe:

> In math notation you can write 0 < x < 6, and in Python, you could do the same, or you could split these into separate comparisons. Here're two examples: ...

**Comment by hockeybuggy** [comment]
Hey @pennyan. That seems like a great suggestion to me (disclaimer: I am not affiliated with LLC, just trying to help out).

Do you feel like opening a PR to that affect? Or I could open one if you prefer?

**Comment by pennyan** [comment]
Hi @hockeybuggy , oh oh, I see. I thought you are the maintainer for this repository. Thanks for trying to help out! I will generate a PR. Cheers!

**Comment by dmilliken** [comment]
Thanks for your comments! We are working on making changes to this content right now and I'll keep this in mind. I have closed the PR.
