### ISSUE TITLE
Provide an answer key for the final exercise

### ISSUE THREAD

**Issue by evidens** [ladieslearningcode/llc-intro-to-python#4]
As an instructor or participant, I would find it useful to have an answer key against which to check my approach (recognising that there are many approaches). Furthermore, it would be nice to see an applied example allowing you to write out to file as well.

- [x] Provide answer key
- [x] Provide a 'next steps' example with writing out to file
- [x] Provide a reference and basic instructions to work with unicode CSV data (as you would need working with French or pretty much any language other than English)

**Comment by christinatruong** [comment]
Merged in pull request #5.  Thanks @evidens!
