### ISSUE TITLE
Moving to Python 3?

### ISSUE THREAD

**Issue by fdosani** [ladieslearningcode/llc-intro-to-python#57]
Hi there,

I was wondering if LLC would be open to moving the material to use Python 3 vs 2.
Since 2 is almost at its end of life (https://pythonclock.org/), it might be beneficial to students to learn the 3.6+ syntax.

I'm happy to submit a PR for this if the team is open to it. 😄

**Comment by dmilliken** [comment]
Hey there! Actually we are working on this, here is the open branch: https://github.com/ladieslearningcode/llc-intro-to-python/tree/llc-intro-to-python-upgrade-to-python-3

Your comment comes at the perfect time because we are having problems with the installation process on apple computers. If you are a mac user I would love some help to smooth that out as I do not own one.

**Comment by fdosani** [comment]
Absolutely. Happy to help. 

Personally and professionally I've always taken a liking to the Anaconda distribution. It solves some of the issues with permissions (can be installed in a local directory without needing Admin privileges), and also leaves the system version of Python intact on a Mac. https://conda.io/miniconda.html

Alternatively you can just have people `brew` install Python3, but form my experience as being a mentor it might slow the class down as it is a "extra" step. Or stick with similar Windows instructions and install from python.org: https://www.python.org/downloads/mac-osx/

Was there a particular part which you needed help with? I can try things out on my Mac if needed.

**Comment by dmilliken** [comment]
Superb!
Please look at the installation slide on that branch. We are pointing them to that URL https://www.python.org/downloads/mac-osx/. 

On windows, installing python 3.6 and then pycharm from the provided links gets the desired result -> pycharm picks up the version 3.6 as the default interpreter and the learners can be on their way.

However when I had someone test this on an apple computer it picked up the interpreter for version 2.7 by default (macs come with a partial version of 2.7 or something?) and the users have to manually configure a virtual environment. Obviously this is too much for a beginner, we want the installation for both to be point-and-shoot simple. 

I thought 
a) if apple people uninstalled 2.7, maybe pycharm would configure 3.6 automatically -- maybe you could test this hypothesis or,
b) take a look at the installation options for pycharm on a mac, see if the default interpreter version is an option?

**Comment by fdosani** [comment]
The Python 2.7 which comes with all Macs is a system Python version. Its critical to OS processes and is the main reason it is discouraged to use or modify that one. If you do something unintentional you could brick your machine 😢 

Maybe something like this is would help within Pycharm? https://www.jetbrains.com/help/pycharm-edu/configuring-available-python-interpreters.html#view_list

**Comment by dmilliken** [comment]
Oh that is most unhappy news. :( 
We sort of wanted to avoid extra technical configuration. I would consider it a blocker to doing the upgrade. 

Maybe this pain for apple users would be temporary. What will apple machines do when 2.7 is retired, will an updated OS version provide a 3.x version of python? 

Also could we explore option (b) if there are additional pycharm installation options when multiple interpreters are available?

**Comment by fdosani** [comment]
It might just stick around in a legacy mode. I believe it is Apple's own version of Python. so they would patch it etc. Python 2 will still be around, it just wont get any improvements / security updates. Eventually I would assume they will upgrade to Python 3, but it would be a big shift.

Let me see if I can install PyCharm and Python 3 from Python.org and getting it working.

**Comment by dmilliken** [comment]
Hah. SMH, leave it to apple to want to have their own version of everything.

**Comment by fdosani** [comment]
So it seems like it isn't too difficult to setup (similar path to Windows). Was able to install Python 3.7 via the GUI interface which installs it under: 

```bash
~ which python3
/usr/local/bin/python3
```

And then when opening a new project I can select the environment I want. Either the 3.7 (system interpreter) or a new `venv`

<img width="776" alt="screen shot 2018-06-28 at 9 47 25 am" src="https://user-images.githubusercontent.com/10391670/42038319-abdc596a-7ab8-11e8-87e1-32b8f93457c2.png">

**Comment by dmilliken** [comment]
We provide a project for the learners to open (it's in the zip package). Could you try opening that and see what the options are?

**Comment by fdosani** [comment]
Seems like you need to go to `Preferences --> Project: llc-intro-to-python-master --> Project Interpreter`. From there you get the following screen and clicking on the highlight area lets you add the new environment or use an existing one. So a couple of extra steps.

<img width="922" alt="screen shot 2018-06-28 at 9 57 01 am" src="https://user-images.githubusercontent.com/10391670/42038860-f976f062-7ab9-11e8-9695-1b66d8666752.png">

**Comment by dmilliken** [comment]
Yep! Just paste them here, I'll make up the slide and then just get you to review it.

**Comment by fdosani** [comment]
@dmilliken 

1 . Assuming you have a opened the project folder `llc-intro-to-python-master`

2. Select `PyCharm -- > Preferences...`
<img width="492" alt="screen shot 2018-06-28 at 2 49 25 pm" src="https://user-images.githubusercontent.com/10391670/42054509-916a161a-7ae2-11e8-9e93-5b929cb904e7.png">

3. A new Preferences dialog window should appear. 

4. Select the project and then `Project Interpreter `
<img width="489" alt="screen shot 2018-06-28 at 2 52 08 pm" src="https://user-images.githubusercontent.com/10391670/42054664-fee3d7d0-7ae2-11e8-9ceb-648d579ea848.png">

5. Depending on your setup you may or may not have a `Project Interpreter` selected from the drop down menu.
<img width="681" alt="screen shot 2018-06-28 at 2 56 09 pm" src="https://user-images.githubusercontent.com/10391670/42054849-81aba0ee-7ae3-11e8-9f1c-d53ed13aabb5.png">

6. Beside the drop down is a little cog which you can select and click add
<img width="596" alt="screen shot 2018-06-28 at 2 59 32 pm" src="https://user-images.githubusercontent.com/10391670/42055015-e9db737e-7ae3-11e8-966d-e2bf408c3972.png">

7. Another dialog should pop up now called `Add Python Interpreter`
<img width="890" alt="screen shot 2018-06-28 at 3 00 16 pm" src="https://user-images.githubusercontent.com/10391670/42055065-10273a72-7ae4-11e8-9991-f1a54eb5b88f.png">

8. Select `System Interpreter` on the left hand side and then select the Python 3.6 you installed in the previous setup. This will typically be:  `/usr/local/bin/python3.6`.

9. Click OK through all the windows and you should see something as follows for the `Preference` dialog
<img width="784" alt="screen shot 2018-06-28 at 3 05 46 pm" src="https://user-images.githubusercontent.com/10391670/42055347-da979a40-7ae4-11e8-8fd1-8733339e4bb3.png">

10. Once you are back into the man project window, your Python console can be restarted (rerun) 
<img width="63" alt="screen shot 2018-06-28 at 3 11 10 pm" src="https://user-images.githubusercontent.com/10391670/42055591-965643c6-7ae5-11e8-9abd-3dfd73d8f0dd.png">
 and you should get the the following:
<img width="346" alt="screen shot 2018-06-28 at 3 07 36 pm" src="https://user-images.githubusercontent.com/10391670/42055442-258cf342-7ae5-11e8-93ba-33f3468376dd.png">

**Comment by dmilliken** [comment]
How thorough! Thank you!

**Comment by dmilliken** [comment]
Hey there, please take a look at these slides and make sure I captured everything: https://github.com/ladieslearningcode/llc-intro-to-python/tree/llc-intro-to-python-upgrade-to-python-3

Commit: https://github.com/ladieslearningcode/llc-intro-to-python/commit/028c2a420ee5cfd7409701707c74f6cee6ec6b16

I added a folder /installation since it was getting out of hand. 🙃  It's linked from the first slide in the instructor's deck.

**Comment by fdosani** [comment]
LGTM! 👍

**Comment by dmilliken** [comment]
Closing issue - upgrade is done & ready for french translation / merge to master.
