### ISSUE TITLE
Update materials to use Python 3

### ISSUE THREAD

**Issue by neganp** [ladieslearningcode/llc-intro-to-python#59]
Python 2 will [not be maintained past 2020](https://www.python.org/dev/peps/pep-0373/#maintenance-releases). There aren't many differences as far as beginners are concerned, but it would be better to teach a version that will have a longer life.

**Comment by neganp** [comment]
I'd be happy to work on this if the maintainers feel it would be worthwhile.

**Comment by dmilliken** [comment]
Hey there! This work has been done, just waiting on french translation to merge. 

Branch: https://github.com/ladieslearningcode/llc-intro-to-python/tree/llc-intro-to-python-upgrade-to-python-3
